### ISSUE TITLE
⚙️ [기능추가][CICD] main 브랜치 PR 요청시 빌드 체크 github action yaml 파일 추가 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [freeMates/FreeMates_Backend#85]
## 📝 현재 문제점

- 현재 빌드가 정상적으로 이루어지는지 PR을 통해서 확인이 불가능함

## 🛠️ 해결 방안 / 제안 기능

- 정상작동하는지 확인하는 github action yaml 코드 필요

## 🙋‍♂️ 담당자

- 백엔드: @Cassiiopeia 
- 프론트엔드: 이름
- 디자인: 이름

**Comment by Cassiiopeia** [comment]
### GitHub Actions의 기본 GITHUB_TOKEN에 PR에 댓글을 작성할 수 있는 권한이 없는 문제 발생
<img width="564" alt="Image" src="https://github.com/user-attachments/assets/3f51d0a9-9cd1-4450-821b-580b50f9515d" />

```
# 권한 설정
permissions:
  contents: read
  pull-requests: write
  issues: write
```

### 권한 설정 추가

추가설명: ${{ secrets.GITHUB_TOKEN }}은 특별한 토큰으로, 별도로 발급받을 필요가 없음 GitHub Actions를 실행할 때 자동으로 GitHub에서 생성해주는 토큰임
