### ISSUE TITLE
[기능추가][PR] coderabbitai AI 코드리뷰봇 추가

### ISSUE THREAD

**Issue by Cassiiopeia** [freeMates/FreeMates_Backend#91]
## 📝 현재 문제점

- PR리뷰가 너무 빈약합니다. 개발속도와 처리속도를 증가하기위해 coderabbitai를 등록해야합니다
- 저희가 놓치고있는 부분이 있을수있습니다 

## 🛠️ 해결 방안 / 제안 기능

- yaml 루트 프로젝트 추가 및 coderabbit 내부 설정 repo 추가 필요
- 모든 말을 맹신하지는 마시고 한번 참고하는게 좋더라구요
- 이런 생각을 안해봤네? 이런것. 이런거 수정하면좋겠다 그런것.

## 🙋‍♂️ 담당자

- 백엔드: @Cassiiopeia @daye200 
- 프론트엔드: 이름
- 디자인: 이름

**Comment by Cassiiopeia** [comment]
```
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ko-KR"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
```

루트에 설정 파일 추가 완료
